import { User } from '@/types';

export const mockUsers: User[] = [
  {
    id: 'ADM001',
    name: 'Sarah Jenkins',
    email: 'admin@amraleaf.com',
    role: 'admin',
    department: 'Cybersecurity Operations',
    status: 'active',
    lastActivity: '2026-08-17T13:45:00Z',
  },
  {
    id: 'EMP001',
    name: 'Liam Vance',
    email: 'employee@amraleaf.com',
    role: 'employee',
    department: 'Finance & Accounts',
    status: 'active',
    lastActivity: '2026-08-17T12:30:00Z',
  },
  {
    id: 'EMP002',
    name: 'Amina Al-Mansoor',
    email: 'amina.al@amraleaf.com',
    role: 'employee',
    department: 'Human Resources',
    status: 'active',
    lastActivity: '2026-08-16T17:15:00Z',
  },
  {
    id: 'EMP003',
    name: 'Chen Wei',
    email: 'chen.wei@amraleaf.com',
    role: 'employee',
    department: 'Software Engineering',
    status: 'active',
    lastActivity: '2026-08-17T09:12:00Z',
  },
  {
    id: 'EMP004',
    name: 'Elena Rostova',
    email: 'elena.rostova@amraleaf.com',
    role: 'employee',
    department: 'Sales & Marketing',
    status: 'active',
    lastActivity: '2026-08-15T11:00:00Z',
  },
  {
    id: 'EMP005',
    name: 'Marcus Brody',
    email: 'marcus.brody@amraleaf.com',
    role: 'employee',
    department: 'Operations',
    status: 'active',
    lastActivity: '2026-08-17T10:45:00Z',
  },
  {
    id: 'EMP006',
    name: 'Priya Nair',
    email: 'priya.nair@amraleaf.com',
    role: 'employee',
    department: 'Customer Success',
    status: 'active',
    lastActivity: '2026-08-14T15:20:00Z',
  },
  {
    id: 'EMP007',
    name: 'Jackson Frost',
    email: 'jackson.frost@amraleaf.com',
    role: 'employee',
    department: 'IT Support & Administration',
    status: 'active',
    lastActivity: '2026-08-17T11:55:00Z',
  },
  {
    id: 'EMP008',
    name: 'Isabella Torrez',
    email: 'isabella.torrez@amraleaf.com',
    role: 'employee',
    department: 'Legal & Compliance',
    status: 'inactive',
    lastActivity: '2026-08-10T14:30:00Z',
  }
];
